// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gejgafjsuvjjcxnouxwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlamdhZmpzdXZqamN4bm91eHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzY2ODIsImV4cCI6MjA3MTgxMjY4Mn0.EjJMIewLoJ5SI152MndH46OTo7IwX0IzBWN3DNtxYD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});